name: CI workflow
# Build the code, run the tests, fail fast (or succeed fast).

on:
  push:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.3.2"]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry versions
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install the project to test the pyproject.toml configuration
        run: poetry install --no-interaction

      - name: Run the tests using the test target in the Makefile
        run: make test
