name: CI workflow
# Build the code, run the tests, fail fast (or succeed fast).

on:
  push:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the tests using the test target in the Makefile
        run: |
          python3 -m venv .venv
          ls -al
          source .venv/bin/activate
          pip3 install --editable .
          pip3 install ."[tests]"
          pytest

# release-to-qa
# Manual release
# Check for version bump?
# Build distribution
# push to test.pypi.org
# Install from test.pypi.org
# Validate package works somehow

# release-to-prod
# Manual release
# Check for version bump?
# Build distribution
# push to test.pypi.org
# Install from test.pypi.org
# Validate package works somehow
