name: Build and publish to pypi repo

on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub Environment name to release to. Valid options are 'test' or 'production'."
        required: true
        type: string
      pypi_url:
        description: "URL to publish to. ie https://test.pypi.org/legacy/ or https://pypi.org/p/<your-pypi-project-name>"
        required: true
        type: string
      python_version:
        description: "Python version to build with"
        required: false
        type: string
        default: "3.11"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: macos-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup Python versions
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Build the package
      run: |
        make install
        make build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.pypi_url }}
        print-hash: true
